"""комментарий к миграции

Revision ID: 723c90d83b61
Revises: e4bb7eb2ed1d
Create Date: 2026-09-30 20:34:31.719581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '723c90d83b61'
down_revision: Union[str, Sequence[str], None] = 'e4bb7eb2ed1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partsrequest', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'CREATED', 'IN_REVIEW', 'APPROVED', 'SHIPPED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='requeststatus'),
               type_=sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'SHIPPED', 'COMPLETED', name='requeststatus', native_enum=False),
               existing_comment='Статус запроса',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partsrequest', 'status',
               existing_type=sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'SHIPPED', 'COMPLETED', name='requeststatus', native_enum=False),
               type_=postgresql.ENUM('DRAFT', 'CREATED', 'IN_REVIEW', 'APPROVED', 'SHIPPED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='requeststatus'),
               existing_comment='Статус запроса',
               existing_nullable=False)
    # ### end Alembic commands ###
