"""комментарий к миграции

Revision ID: b37d6284a5b9
Revises: 
Create Date: 2026-09-30 21:53:42.888839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37d6284a5b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=True, comment='Username'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='root'),
    sa.Column('hashed_password', sa.String(), nullable=True, comment='Хеш пароля'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicecenter',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название АСЦ'),
    sa.Column('contact_person', sa.String(length=255), nullable=False, comment='Контактное лицо'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Номер телефона'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email'),
    sa.Column('address', sa.Text(), nullable=False, comment='Адрес доставки деталей'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Статус активности'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partsrequest',
    sa.Column('status', sa.Enum('CREATED', 'IN_REVIEW', 'COLLECTING', 'SHIPPED', 'RECEIVED', name='requeststatus', native_enum=False), nullable=False, comment='Статус запроса'),
    sa.Column('is_urgent', sa.Boolean(), nullable=False, comment='Платный/гарантийный ремонт'),
    sa.Column('work_order_number', sa.String(length=100), nullable=True, comment='№ акта'),
    sa.Column('device_model', sa.String(length=255), nullable=False, comment='Модель устройства'),
    sa.Column('serial_number', sa.String(length=100), nullable=False, comment='Серийный номер техники'),
    sa.Column('comment_asc', sa.Text(), nullable=True, comment='Примечание'),
    sa.Column('asc_id', sa.Integer(), nullable=False, comment='АСЦ'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.ForeignKeyConstraint(['asc_id'], ['servicecenter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partsrequest')
    op.drop_table('servicecenter')
    op.drop_table('user')
    # ### end Alembic commands ###
