"""edit_12

Revision ID: e4bb7eb2ed1d
Revises: 
Create Date: 2026-09-15 00:23:50.370016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bb7eb2ed1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partsrequest', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'SHIPPED', 'COMPLETED', name='requeststatus'),
               existing_comment='Статус запроса',
               postgresql_using='status::requeststatus',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partsrequest', 'status',
               existing_type=sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'SHIPPED', 'COMPLETED', name='requeststatus'),
               type_=sa.VARCHAR(length=9),
               existing_comment='Статус запроса',
               postgresql_using='status::varchar',
               existing_nullable=False)
    # ### end Alembic commands ###
